config/routes.rb
Rails.application.routes.draw do
  resources :user_details
  devise_for :users
  resources :order_details
  resources :orders
  resources :users
  resources :authors
  resources :books
  resources :categories
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/order_details/new/:id' => "order_details#new", :as => 'order_detail_add'
  get '/order/checkout/:id' => "orders#checkout", :as => 'checkout_order'
  root "application#index"
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_detail
    belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy checkout ]

  def checkout
    @order_details = OrderDetail.where("order_id=?",@order.id)
    user = User.find(@order.user_id)
    @total_price = 0
    @price = 0
    @order_details.each do |item|
      book_price = Book.find(item.book_id).price
      @total_price+=book_price*item.quantity
    end
    @price = @total_price*(100-User.levels[user.level])
  end
  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
    @order_details = OrderDetail.where("order_id=?",params[:id])
    @order_detail = OrderDetail.new
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    order_details = OrderDetail.where("order_id=?",@order.id)
    order_details.each do |o|
      o.destroy
    end
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id, :address)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.select :user_id ,  User.all.collect { |c| [c.name, c.id] },{}%>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>ID:</strong>
    <%= order.id %>
  </p>
  <p>
    <strong>User:</strong>
    <%= order.user.name %>
  </p>
  
  <p>
    <strong>Address:</strong>
    <%= order.address %>
  </p>

</div>

app/views/orders/_order_item.html.erb
<div id="<%= dom_id order_detail %>">
  <p>Book name: <%= Book.find(order_detail.book_id).title %></p>
  <p>Price: <%= Book.find(order_detail.book_id).price%>$ | Quantity: <%= order_detail.quantity %> |   <%= link_to "Edit", edit_order_detail_path(order_detail) %> 
</p>
</div>
<hr>

app/views/orders/checkout.html.erb
<h1>Checkout</h1>
<br>
<h4>Cart</h4>
<div id="order_details">
  <% @order_details.each do |order_detail| %>
    <%= render "order_item", order_detail:order_detail %>
  <% end %>
</div>
<h4>Total</h4>
<div>
  <p>Order Total: <%= @total_price%>$</p>
  <p>Total Payment: <%= @price%>$</p>
  <p>--> But it's free today!!!</p>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>
<h3>Order Information</h3>
<%= render @order %>
<%# <%= "length is"+@order_details.length.to_s%> 
<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>|
  <%= link_to "New order", new_order_path %>
  <%= button_to "Destroy this order", @order, method: :delete %>
</div>
<br><br>
<h3>Cart</h3>
<div id="order_details">
  <% @order_details.each do |order_detail| %>
    <%= render "order_item", order_detail:order_detail %>
  <% end %>
</div>
  <%= button_to "Add more", order_detail_add_path(@order.id), method: :get%>
  <%= button_to "Checkout", checkout_order_path(@order.id), method: :get%>