config/routes.rb
Rails.application.routes.draw do
  resources :user_details
  devise_for :users
  resources :order_details
  resources :orders
  resources :users
  resources :authors
  resources :books
  resources :categories
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/order_details/new/:id' => "order_details#new", :as => 'order_detail_add'
  get '/order/checkout/:id' => "orders#checkout", :as => 'checkout_order'
  root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :posts
    before_validation :set_defaults
  
    private
    def set_defaults
      name = "First Last" if name.blank?
    end
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category 
    belongs_to :author
    validates :price, numericality: { greater_than: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    has_many :books

    enum category_type: {
      "General" => '0',
      "News" => '1',
      "Sports" => '2',
    }
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_detail
    belongs_to :user
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :book
    validates :quantity, numericality: { greater_than: 1 }
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category 
    belongs_to :author 
    enum status: {
        "unpublished" => false,
        "published" => true
      }
    # default_scope -> {where (status:true).order(created_at: :desc)}
    scope :published, lambda {where(:status=>true)}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :order
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
    belongs_to :user
    enum level: {
        "Standard" => 0.02,
        "Premium" => 0.05,
        "Vip" => 0.1,
      }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    # Time.now.strftime("%d/%m/%Y %H:%M")
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
    params.require(:book).permit(:title, :description, :price, :publish_at, :author_id, :category_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :kind, :author_id, :category_id,:status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ index show edit update ]

  # GET /users or /users.json
  def index
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



    # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(current_user.id)
      end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
  <div class="container">
  <ul class="nav">
  <li class="nav-item">
    <a class="nav-link <%current_page?(root_path) ? 'active' : ''%>" aria-current="page" href="<%= root_path %>"><%= image_tag("kiwi16.png")%></a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%current_page?(posts_path) ? 'active' : ''%>" href="<%= posts_path %>">Posts</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%current_page?(categories_path) ? 'active' : ''%>" href="<%= categories_path %>">Categories</a>
  </li>
    <li class="nav-item">
    <a class="nav-link <%current_page?(books_path) ? 'active' : ''%>" href="<%= books_path %>">Books</a>
  </li>
    <li class="nav-item">
    <a class="nav-link <%current_page?(authors_path) ? 'active' : ''%>" href="<%= authors_path %>">Authors</a>
  </li>
    <li class="nav-item">
    <a class="nav-link <%current_page?(users_path) ? 'active' : ''%>" href="<%= users_path %>">Users</a>
  </li>
    <li class="nav-item">
    <a class="nav-link <%current_page?(orders_path) ? 'active' : ''%>" href="<%= orders_path %>">Orders</a>
  </li>
    <li class="nav-item">
    <a class="nav-link <%current_page?(order_details_path) ? 'active' : ''%>" href="<%= order_details_path %>">Order Details</a>
  </li>

<% if user_signed_in? %>
  <li class="nav-item dropdown ms-auto">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.email %>
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li>
            <a class="nav-link text-dark" href="<%= users_path %>">Profile</a>
        </li>
        <li>
            <%= button_to 'Sign out',destroy_user_session_path, method: :delete, class:"btn btn-sm nav-link text-dark"%>
        </li>
      </ul>
    </li>
<% else %>
    <li class="nav-item ms-auto">
    <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
  </li>
  <% end %>

  
</ul>
<hr class="bg-primary border-2 border-top border-primary">
<p> <%#= current_page?(root_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KiwiappFinal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
  </div>
  </body>
</html>